#!/bin/bash

# Usage: sendkey pub_key_file server1 server2 [...]

PUB_KEY_FILE=$1
shift

# send the public key in pubkey_file to one or more servers
# assumes that your login directory on the remote server is your $HOME
for server in "$@"; do
    <"$PUB_KEY_FILE" ssh "$server" "mkdir -p .ssh && cat >> .ssh/authorized_keys"
done
